/**
 *
 * $Id$
 */
package br.ufms.facom.acctrace.model.validation;

import br.ufms.facom.acctrace.model.Reference;

// TODO: Auto-generated Javadoc
/**
 * A sample validator interface for
 * {@link br.ufms.facom.acctrace.model.OWLOntology}. This doesn't really do
 * anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OWLOntologyValidator {

	/**
	 * Validate.
	 * 
	 * @return true, if successful
	 */
	boolean validate();

	/**
	 * Validate path.
	 * 
	 * @param value
	 *            the value
	 * @return true, if successful
	 */
	boolean validatePath(String value);

	/**
	 * Validate reference.
	 * 
	 * @param value
	 *            the value
	 * @return true, if successful
	 */
	boolean validateReference(Reference value);

	/**
	 * Validate id.
	 * 
	 * @param value
	 *            the value
	 * @return true, if successful
	 */
	boolean validateId(String value);
}
