/**
 *
 * $Id$
 */
package br.ufms.facom.acctrace.model.validation;

// TODO: Auto-generated Javadoc
/**
 * A sample validator interface for
 * {@link br.ufms.facom.acctrace.model.RequirementRepository}. This doesn't
 * really do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RequirementRepositoryValidator {

	/**
	 * Validate.
	 * 
	 * @return true, if successful
	 */
	boolean validate();

	/**
	 * Validate id.
	 * 
	 * @param value
	 *            the value
	 * @return true, if successful
	 */
	boolean validateId(String value);
}
